[workspace]
members = ["crates/ehrust", "crates/libeh"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["pboymt"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
